module.exports = {
  FIRST_CMD_ARG: 2,
  FIRST_ELEMENT: 0,
  SECOND_ELEMENT: 1,
  FIRST_NUMBER_CODE: 48,
  LAST_NUMBER_CODE: 57,
  FIRST_LOWER_CHAR_CODE: 97,
  LAST_LOWER_CHAR_CODE: 122,
  FIRST_UP_CHAR_CODE: 65,
  LAST_UP_CHAR_CODE: 90,
  ALPHABET_LENGTH: 26,
  LINE_SYMBOL: "-"
};
